services:
  next:
    container_name: next
    image: maxproske/cvepets-next:latest
    build:
      context: ./next
      dockerfile: release.Dockerfile
      # Environment variables must be present as arguments at build time
      # https://github.com/vercel/next.js/discussions/14030
      args:
        IS_QA: ${IS_QA}
        OV_PASSWORD: ${OV_PASSWORD}
    restart: always
    networks:
      - cvepets
    ports:
      - 80:3000 # Port 3000 is likely already in use
      - 443:3000