version: "3"

services:
  openvas:
    container_name: openvas
    image: atomicorp/openvas
    # Persist data if container is stopped 
    volumes:
      - openvas:/var/lib/openvas/mgr
      - ovsock:/var/run
    environment:
      OV_PASSWORD: ${OV_PASSWORD}
    ports:
      - 443:443 # Port 443 is likely already in use
    restart: always
    networks:
      - cvepets

  mixeway:
    container_name: mixeway
    build:
      context: ./mixeway
      dockerfile: Dockerfile
    # Use unix socket from openvas container
    volumes:
      - ovsock:/var/run/openvas:rw
    ports:
      - 8443:8443
    restart: always
    depends_on: 
      - openvas
    networks:
      - cvepets

volumes:
  openvas:
  ovsock: